base_channels: 32
channels_multiple: [ 1, 2, 4 ]
latent_dim: 8
alpha: 1.0
alpha_decay_rate: 0.05
beta: 0.0015
spatial_shape: [512, 512, 512]
learning_rate: 1e-4
params:
  base_channels: ${vae.base_channels}
  channels_multiple: ${vae.channels_multiple}
  latent_dim: ${vae.latent_dim}
  alpha: ${vae.alpha}
  alpha_decay_rate: ${vae.alpha_decay_rate}
  beta: ${vae.beta}
  spatial_shape: ${vae.spatial_shape}